###########
### 공통 ###
###########
server:
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /samp

spring:
  profiles:
    active: local;

feign:
  client:
    config:
      default:
        connectTimeout: 3000  # feign의 전역 timeout 설정 : 20초
        readTimeout: 20000
        loggerLevel: FULL ##basic

logging:
  level:
    root: info
    com:
      samp: debug