###########
### 공통 ###
###########
#server:
#  tomcat:
#    uri-encoding: UTF-8
#  servlet:
#    context-path: /samp

spring:
  application:
    name: samp
  profiles:
    active: local

logging:
  level:
    root: info
    com:
      samp: debug